language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sadjana/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sadjana/docker-react npm run test

